### send text message
POST http://localhost:3000/api/send-message HTTP/1.1
Content-Type: application/json

{
    "number":"923412727290",
    "message": "Hello World"
}

### authenticate user
POST http://localhost:3000/authenticate HTTP/1.1
Content-Type: application/json

{
    "username":"user",
    "password": "anypass"
}

### get products
GET http://localhost:3000/api/data/get_products?name=iphone xr&author=971569467623 HTTP/1.1
authorization: auth-jwt
Content-Type: application/json

### get products
GET http://localhost:3000/api/data/get_products_excel?&name=iphone xr&author=jubel HTTP/1.1
authorization: auth-jwt
Content-Type: application/json

### get config
GET http://localhost:3000/api/config HTTP/1.1
Content-Type: application/json
authorization: jwt AUTH TOKEN

### get config by key
GET http://localhost:3000/api/config?key=newMessageInterval HTTP/1.1
Content-Type: application/json
authorization: auth-jwt

### save config
POST  http://localhost:3000/api/config/save HTTP/1.1
Content-Type: application/json
authorization: auth-jwt

{
    "pairs":[{"key":"newMessageInterval","value":"10"}, {"key":"openai_key","value":"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"}]
}

### generate deal initiate message
GET http://localhost:3000/api/ai/generate-proposal
Content-Type: application/json
authorization: auth-jwt

{
    "intent": "buy",
    "product": "iphone xr",
    "ram": "4gb",
    "storage": "64gb",
    "color": "black"
}

### get prd buy sell analytics
GET http://localhost:3000/api/analytics/product-buy-sell?time_frame=daily

### add user
POST http://localhost:3000/api/add_user HTTP/1.1
Content-Type: application/json

{
    "secret":"",
    "username":"user",
    "password": "anypass"
}

### get groups
GET http://localhost:3000/api/whatsapp/groups

### new collection
POST http://localhost:3000/api/whatsapp/group-collections HTTP/1.1
Content-Type: application/json

{
    "name":"test2"
}

### get group collections
GET http://localhost:3000/api/whatsapp/group-collections


### rename collection
PUT http://localhost:3000/api/whatsapp/group-collections HTTP/1.1
Content-Type: application/json

{
    "collectionId":3,
    "newName":"test4"
}

### delete collection
DELETE http://localhost:3000/api/whatsapp/group-collections?collectionId=3
Content-Type: application/json

{
    "collectionId":3
}



### add group to collection
POST http://localhost:3000/api/whatsapp/group-collections/groups HTTP/1.1
Content-Type: application/json

{
    "collectionId":2,
    "groupIds":[
        "120363144114387125@g.us",
        "120363162096958727@g.us",
        "120363142734141560@g.us",
        "120363162723246463@g.us",
        "120363162431563498@g.us",
        "anygroup"
    ]
}

### remove group from collection
DELETE http://localhost:3000/api/whatsapp/group-collections/groups?collectionId=2&groupId=120363144114387125@g.us


### get groups in collection
GET http://localhost:3000/api/whatsapp/group-collections/groups?collectionId=2
Content-Type: application/json

### get groups not in collection
GET http://localhost:3000/api/whatsapp/group-collections/groups-not-in?collectionId=2
Content-Type: application/json

### delete ad by id
DELETE http://localhost:3000/api/ads?id=12 HTTP/1.1

### DELETE IMAGE
DELETE http://localhost:3000/api/images?id=9 HTTP/1.1